-- ═══════════════════════════════════════════════════════════════════════════
-- lo_payroll_aliases — the name equivalences a human has confirmed
-- ═══════════════════════════════════════════════════════════════════════════
--
-- WHAT THIS IS FOR
--
-- The payroll writes a person's name one way and loan_officials writes it
-- another, and neither is wrong:
--
--     payroll          "LAINO CHEGWIN, GIAN L"   "BADOVINAC, STEVEN P"
--     loan_officials   "Gian Laino"              "Steve Badovinac"
--
-- A rule that requires a shared surname and a shared given name settles 33 of
-- the 46 loan officers with no ambiguity at all. This table exists for the ones
-- it cannot settle, and ONLY for those.
--
-- WHY A TABLE AND NOT A SIMILARITY SCORE
--
-- Because the payroll holds "CASTRO, JULY M" and "CASTRO, JUSETH M", two
-- different people, and "Julymar Mar Castro" is one of them. Any fuzzy ranking
-- has a real chance of picking the wrong one, and a wrong match is worse than
-- no match: it hands one person's salary to another and nothing on screen says
-- so. Every row here is a decision somebody made and can be argued with.
--
-- WHY A TABLE AND NOT A CONSTANT IN THE CODE
--
-- It changes when people are hired, not when the software changes, so it must
-- not need a deploy. And it is small: two rows are known to be needed today.
--
--     "BADOVINAC, STEVEN P"   -> "Steve Badovinac"     (Steve / Steven)
--     "CASTRO, JULY M"        -> "Julymar Mar Castro"  (the decoy above)
--
-- They are NOT inserted here. Adding them is a judgement about who two people
-- are, and that belongs to whoever knows, not to a migration.
--
-- The other eleven unmatched officers are not this table's problem: their
-- surname does not appear in the compensation accounts at all, and seven of
-- them appear nowhere in the entire P&L. They have no compensation recorded,
-- which is a finding rather than a gap.
--
-- NOT EXECUTED. Review and apply it yourself, as with the backups table.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists finance_division.lo_payroll_aliases (
  id            uuid primary key default gen_random_uuid(),

  -- The description exactly as the payroll writes it, kept verbatim so a row
  -- can be traced back to the ledger by eye. Matching normalizes case and
  -- accents anyway, so the stored form is for humans, not for the join.
  payroll_name  text not null,

  -- The loan_officer exactly as loan_officials writes it.
  loan_officer  text not null,

  -- Why somebody decided these are the same person. Not decoration: the next
  -- reader has to be able to disagree with the reason, and "Steve is Steven"
  -- and "confirmed with HR" are very different grounds.
  note          text,

  created_at    timestamptz not null default now(),
  created_by    text,

  -- One payroll person maps to one officer and one officer to one payroll
  -- person. Both directions are constrained because the matcher requires a 1:1
  -- pairing: loan_officials already carries the same person under two spellings
  -- ("Galo Rizzo" and "Galo Rizzo Hinojosa"), and letting the alias table add
  -- another many-to-one would double-count that person's pay in the totals.
  constraint lo_payroll_aliases_payroll_unique unique (payroll_name),
  constraint lo_payroll_aliases_officer_unique unique (loan_officer)
);

comment on table finance_division.lo_payroll_aliases is
  'Human-confirmed equivalences between a payroll check_description and a loan_officials.loan_officer. Only for names the surname+given rule cannot settle; never generated by similarity.';

comment on column finance_division.lo_payroll_aliases.note is
  'Why these are the same person. Required reading before trusting the row.';

-- ── Row level security ─────────────────────────────────────────────────────
-- Same shape as manual_assignment_backups: locked by default, service_role
-- only. The application reads it through the server client; no browser session
-- ever touches it directly.

alter table finance_division.lo_payroll_aliases enable row level security;

drop policy if exists lo_payroll_aliases_service_role on finance_division.lo_payroll_aliases;
create policy lo_payroll_aliases_service_role
  on finance_division.lo_payroll_aliases
  for all
  to service_role
  using (true)
  with check (true);

grant usage on schema finance_division to service_role;
grant select, insert, update, delete on finance_division.lo_payroll_aliases to service_role;

-- ── The two rows that are known to be needed ───────────────────────────────
-- Left commented on purpose. Uncomment only after confirming that each pair is
-- one person; the note is what makes that confirmation reviewable later.
--
-- insert into finance_division.lo_payroll_aliases (payroll_name, loan_officer, note) values
--   ('BADOVINAC, STEVEN P', 'Steve Badovinac',
--    'Same person: Steve is the short form of Steven. 22 closings, $10.7M; pay sits in Sign-On Bonus and Guarantee.'),
--   ('CASTRO, JULY M', 'Julymar Mar Castro',
--    'Same person. CONFIRM BEFORE USING: the payroll also holds CASTRO, JUSETH M, a different person, and the two are one letter apart in the given name.');
